// ─── Mock data for development (replace with Supabase queries in production) ──

export const FEATURED_PRODUCTS = [
  {
    id: "1",
    name: "Scarlet & Violet Booster Box",
    category: "sealed",
    subcategory: "booster-box",
    price: 149.99,
    originalPrice: 179.99,
    image: "https://images.pokemontcg.io/sv1/logo.png",
    badge: "HOT",
    set: "Scarlet & Violet",
    language: "English",
    inStock: true,
    stock: 8,
  },
  {
    id: "2",
    name: "Charizard ex Special Collection",
    category: "sealed",
    subcategory: "premium-collection",
    price: 64.99,
    originalPrice: null,
    image: "https://images.pokemontcg.io/sv3/logo.png",
    badge: "NEW",
    set: "Obsidian Flames",
    language: "English",
    inStock: true,
    stock: 12,
  },
  {
    id: "3",
    name: "151 Korean Booster Box",
    category: "sealed",
    subcategory: "booster-box",
    price: 119.99,
    originalPrice: 139.99,
    image: "https://images.pokemontcg.io/sv3pt5/logo.png",
    badge: "🇰🇷 KR",
    set: "Pokémon 151",
    language: "Korean",
    inStock: true,
    stock: 4,
  },
  {
    id: "4",
    name: "Temporal Forces Elite Trainer Box",
    category: "sealed",
    subcategory: "etb",
    price: 54.99,
    originalPrice: null,
    image: "https://images.pokemontcg.io/sv5/logo.png",
    badge: "NEW",
    set: "Temporal Forces",
    language: "English",
    inStock: true,
    stock: 20,
  },
  {
    id: "5",
    name: "Charizard VSTAR Rainbow Rare",
    category: "single",
    subcategory: "holo-rare",
    price: 34.99,
    originalPrice: null,
    image: "https://images.pokemontcg.io/swsh12pt5/logo.png",
    badge: "⭐ RARE",
    set: "Crown Zenith",
    language: "English",
    inStock: true,
    stock: 3,
  },
  {
    id: "6",
    name: "Pikachu VMAX Alternate Art",
    category: "single",
    subcategory: "alt-art",
    price: 89.99,
    originalPrice: null,
    image: "https://images.pokemontcg.io/swsh4/logo.png",
    badge: "ALT ART",
    set: "Vivid Voltage",
    language: "English",
    inStock: true,
    stock: 1,
  },
];

export const HOT_SINGLES = [
  {
    id: "s1",
    name: "Charizard ex SAR",
    pokemon: "Charizard",
    set: "Obsidian Flames",
    setCode: "OBF",
    number: "223/197",
    rarity: "Special Art Rare",
    language: "English",
    condition: "NM",
    price: 79.99,
    image: "https://images.pokemontcg.io/sv3/logo.png",
    trend: "+12%",
    trending: true,
  },
  {
    id: "s2",
    name: "Mewtwo ex SAR",
    pokemon: "Mewtwo",
    set: "Pokémon 151",
    setCode: "MEW",
    number: "205/165",
    rarity: "Special Art Rare",
    language: "Japanese",
    condition: "NM",
    price: 44.99,
    image: "https://images.pokemontcg.io/sv3pt5/logo.png",
    trend: "+8%",
    trending: true,
  },
  {
    id: "s3",
    name: "Umbreon VMAX Alt Art",
    pokemon: "Umbreon",
    set: "Evolving Skies",
    setCode: "EVS",
    number: "214/203",
    rarity: "Alternate Art",
    language: "English",
    condition: "NM",
    price: 119.99,
    image: "https://images.pokemontcg.io/swsh7/logo.png",
    trend: "+5%",
    trending: true,
  },
  {
    id: "s4",
    name: "Mew VMAX HR",
    pokemon: "Mew",
    set: "Fusion Strike",
    setCode: "FST",
    number: "269/264",
    rarity: "Hyper Rare",
    language: "English",
    condition: "NM",
    price: 59.99,
    image: "https://images.pokemontcg.io/swsh8/logo.png",
    trend: "+3%",
    trending: false,
  },
];

export const CATEGORIES = [
  {
    id: "sealed",
    label: "Sealed Products",
    icon: "📦",
    href: "/shop?category=sealed",
    count: "200+",
    color: "from-purple-600/20 to-purple-800/5",
    border: "hover:border-purple-500/40",
  },
  {
    id: "singles",
    label: "Singles",
    icon: "🃏",
    href: "/singles",
    count: "5,000+",
    color: "from-cyan-600/20 to-cyan-800/5",
    border: "hover:border-cyan-500/40",
  },
  {
    id: "graded",
    label: "Graded Cards",
    icon: "🏆",
    href: "/graded",
    count: "150+",
    color: "from-yellow-500/20 to-yellow-700/5",
    border: "hover:border-yellow-500/40",
  },
  {
    id: "accessories",
    label: "Accessories",
    icon: "🛡️",
    href: "/shop?category=accessories",
    count: "100+",
    color: "from-green-600/20 to-green-800/5",
    border: "hover:border-green-500/40",
  },
  {
    id: "japanese",
    label: "Japanese & Korean",
    icon: "🇯🇵",
    href: "/shop?language=japanese",
    count: "300+",
    color: "from-red-500/20 to-red-700/5",
    border: "hover:border-red-500/40",
  },
  {
    id: "merchandise",
    label: "Merchandise",
    icon: "🧸",
    href: "/shop?category=merchandise",
    count: "50+",
    color: "from-pink-500/20 to-pink-700/5",
    border: "hover:border-pink-500/40",
  },
];

export const UPCOMING_DROPS = [
  {
    id: "d1",
    name: "Stellar Crown Booster Box",
    releaseDate: "2026-06-15",
    image: "https://images.pokemontcg.io/sv7/logo.png",
    preorder: true,
    price: 149.99,
  },
  {
    id: "d2",
    name: "Twilight Masquerade ETB",
    releaseDate: "2026-06-28",
    image: "https://images.pokemontcg.io/sv6/logo.png",
    preorder: true,
    price: 54.99,
  },
  {
    id: "d3",
    name: "Japanese CoroCoro Promo Pack",
    releaseDate: "2026-07-05",
    image: "https://images.pokemontcg.io/swsh12pt5/logo.png",
    preorder: false,
    price: 24.99,
  },
];

export const NAV_LINKS = [
  { label: "Shop",       href: "/shop" },
  { label: "Singles",    href: "/singles" },
  { label: "Graded",     href: "/graded" },
  { label: "Sell to Us", href: "/sell-to-us" },
  { label: "Trade In",   href: "/trade-in" },
  { label: "Live",       href: "/live", badge: "LIVE" },
];
